stages:
  - test
  - deploy

before_script:
  - /opt/chefdk/bin/chef shell-init bash
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/kitchen --version

cookstyle:
  stage: test
  script:
  - /opt/chefdk/embedded/bin/cookstyle
  tags:
    - test-kitchen

foodcritic:
  stage: test
  script:
  - /opt/chefdk/embedded/bin/foodcritic . -X spec -P -f any
  tags:
    - test-kitchen

kitchen:
  stage: test
  script:
   - /opt/chefdk/embedded/bin/kitchen test -d always -c 3
  tags:
    - test-kitchen
