---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7

suites:
  - name: default
    data_bags_path:
      - test/integration/default/data_bags
    environments_path:
      - test/integration/default/environments
    run_list:
      - recipe[sudo_databag::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
